services:
  postgres:
    image: postgres:17.2
    container_name: pg
    restart: always
    environment:
      POSTGRES_PASSWORD: 14141414     
      POSTGRES_USER: dave          
      POSTGRES_DB: mydb               
    ports:
      - "5432:5432"

  hasura:
    image: hasura/graphql-engine:v2.47.0
    container_name: hasura
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - auth
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://dave:14141414@postgres:5432/mydb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: dave12345678
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "123123123123123123123123123123123"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
  auth:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auth
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/app/uploads
   